name: 🚀 Disparar Deploy Externo

on:
  push:
    branches:
      - main

jobs:
  dispatch-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Disparar Workflow no Repositório de Deploy
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: ArthurBitt/repo_listener_teste
          event-type: test
          client-payload: |
            {
              "branch": "${{ github.ref_name }}",
              "repository": "devrenangabriel/ci-cd-test"
            }
